ML/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from leilao import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.Home.as_view(), name='home'),
    path('', include('leilao.urls'), name='leilao'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leilao/urls.py
from django.contrib.auth import views
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from leilao import views

app_name = 'leilao'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('create/', views.CreateProduct.as_view(), name='create'),
    path('search/', views.Search.as_view(), name='search'),
    path('throw/', views.Throw.as_view(), name='throw'),
    path('my-throw/', views.MeusLances.as_view(), name='my-throw'),
    path('my-product/', views.MyProduct.as_view(), name='my'),
    path('update/<pk>/', views.ProductUp.as_view(), name='update'),
]

leilao/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

from django.db import models

class Produto(models.Model):
	name = models.CharField(max_length=255, blank=False, verbose_name='nome')
	keyword = models.CharField(max_length=255, blank=False, verbose_name='palavra chave')
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	startPrice = models.PositiveIntegerField(validators=[MinValueValidator(0)], verbose_name='lançe inicial', default=0)
	ultimoLance = models.PositiveIntegerField(validators=[MinValueValidator(0)], verbose_name='lançe final', default=0)
	Prazo = models.DateField(blank=False,verbose_name='prazo')
	vendido = models.BooleanField(default=False, verbose_name='vendido')
	compradoPor = models.CharField(max_length=255, blank=False, verbose_name='nomeComprador')
	state = models.BooleanField(default=True, verbose_name='ativo')
	image = models.ImageField(blank=True)

	def __str__(self):
		return 'produto'

	class Meta:
		verbose_name = 'produto'
		verbose_name_plural = 'produtos'

class Lance(models.Model):
	produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	lance = models.PositiveIntegerField(validators=[MinValueValidator(0)], verbose_name='lançe', default=0)
	bought = models.BooleanField(default=False, verbose_name='comprado')

	def __str__(self):
		return 'Lançes'

	class Meta:
		verbose_name = 'lançe'
		verbose_name_plural = 'lançes'

leilao/forms.py
from django import forms
from . import models
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField

class ProductForm(forms.ModelForm):

	#finalDate = DateField(widget=AdminDateWidget)
	class Meta:
		model = models.Produto
		fields = ('name', 'keyword', 'image', 'startPrice', 'Prazo',)

leilao/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.http import HttpResponseRedirect
import random
from datetime import date
import datetime
from django.urls import reverse_lazy

from . import models, forms
 
class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

class CreateProduct(generic.CreateView):
	form_class = forms.ProductForm
	success_url = reverse_lazy('home')
	template_name = 'produto.html'
	def get_context_data(self, **kwargs):
		data = date.today()
		atual = date.fromordinal(data.toordinal()+1)
		kwargs['date'] = str(atual)
		return super(CreateProduct, self).get_context_data(**kwargs)

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.user = models.User.objects.get(id=self.request.user.pk)
		obj.save()
		return super(CreateProduct, self).form_valid(form)

class Search(generic.ListView):
	model = models.Produto
	template_name = 'home.html'
	def get_queryset(self):
		if(len(models.Produto.objects.filter(keyword=self.request.GET['q']))):
			return models.Produto.objects.filter(keyword=self.request.GET['q'])
		else:
			lista = [False]
			return lista

class Throw(generic.ListView):
	model = models.Produto
	template_name = 'home.html'
	def get(self, request):
		print(self.request.GET['lance'])
		print(self.request.GET['id'])
		if(models.Lance.objects.filter(user=models.User.objects.get(id=self.request.user.pk), produto=models.Produto.objects.get(id=self.request.GET['id']))):
			models.Lance.objects.filter(produto=models.Produto.objects.get(id=self.request.GET['id'])).update(lance=self.request.GET['lance'])
			models.Produto.objects.filter(id=self.request.GET['id']).update(ultimoLance=self.request.GET['lance'])
		else:
			lance = models.Lance.objects.create(produto=models.Produto.objects.get(id=self.request.GET['id']), user=models.User.objects.get(id=self.request.user.pk), lance=int(self.request.GET['lance']))
			lance.save()
			models.Produto.objects.filter(id=self.request.GET['id']).update(ultimoLance=self.request.GET['lance'])
		return HttpResponseRedirect('/')


class Home(generic.ListView):
	model = models.Produto
	template_name = 'home.html'
	def get_queryset(self):
		dateAtual = date.today()
		for x in models.Produto.objects.all():
			if(x.state == True):
				if(x.Prazo < dateAtual or x.Prazo == dateAtual):
					obj = models.Produto.objects.get(id=x.id)
					models.Produto.objects.filter(id=x.id).update(state=False, vendido=True)
					values = models.Produto.objects.get(id=x.id).ultimoLance
					models.Lance.objects.filter(produto=obj, lance=values).update(bought=True)

		return models.Produto.objects.all()
#leilao
class MeusLances(generic.ListView):
	model = models.Lance
	template_name = 'lances.html'
	def get_queryset(self):
		if(len(self.request.GET) > 0):
			print(self.request.GET['id'])
			models.Lance.objects.filter(id=self.request.GET['id']).delete()
		return models.Lance.objects.filter(user=models.User.objects.get(id=self.request.user.pk))


class MyProduct(generic.ListView):
	model = models.Produto
	template_name = 'myproduct.html'
	def get_queryset(self):
		if(len(self.request.GET) > 0):
			models.Produto.objects.filter(id = self.request.GET['id']).delete()

		return models.Produto.objects.filter(user=models.User.objects.get(id=self.request.user.pk))

class ProductUp(UpdateView):

    model = models.Produto
    template_name = 'produto.html'
    success_url = reverse_lazy('leilao:my')
    form_class = forms.ProductForm

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Base file{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/forms.css' %} "/>
<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/base.css' %} "/>
<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/global.css' %}"/>
<link rel="stylesheet" type="text/css" 
    href="{% static 'admin/css/widgets.css' %}"/>

<script type="text/javascript" 
    src="/admin/jsi18n/"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/core.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/jquery.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/jquery.init.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/actions.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/calendar.js' %}"></script>
<script type="text/javascript" 
    src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>

<style>
.img1 {
    max-width: 100%;
    max-height: 100%;
}

div.center {
  width: 500px;
  height: 200px;
  display: block;
  background-color: #ffffff;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  box-shadow: 1px 1px 10px 1px #888888;
}
div.center4 {
  width: 500px;
  height: 400px;
  display: block;
  background-color: #ffffff;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  box-shadow: 1px 1px 10px 1px #888888;
}
div.center2 {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

div.center3 {
  display: block;
  background-color: #ffffff;
  position: absolute;
  top: 100px;
  left: 33%;
  padding: 20px;
  box-shadow: 1px 1px 10px 1px #888888;
 
}
.input-margin{
    margin-top: 30px;
}
 
 .upper, .lower {
  position: absolute;
  left: 0;
  right: 0;
}

.upper {
  top: 0;
  height: 50%;
  background-color: #fffa65;  
}

.lower {
  bottom: 0;
  height: 50%;
  background-color: #ffffff;    
}
 button {
    background-color: Transparent;
    background-repeat:no-repeat;
    border: none;
    cursor:pointer;
    overflow: hidden;
    outline:none;
}

.box {
  display: inline-block;
  width: 350px;
  height: 200px;
  margin: 1em;
  margin-top: 50px;
  background-color: #ffffff;
  box-shadow: 1px 1px 10px 1px #888888;
}

.block-color{
  background-color: #ffffff;
}

.title-h1{
  position: relative;
  top: 50%;
  transform: translatey(-50%);
}

.text-relative{
    background-color: #ffffff;
    max-width: 300px;
    border-radius: 50px;
    margin: 0px auto;
    padding: 0px;
    word-break: break-all; 
}

.navbar-custom {
  color:#57606f;
  background-color: #fffa65;
}
.color-custom {
  color:#57606f;
}


</style>
  	

</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>

</body>
</html>

templates/confirm.html
{% extends 'base.html' %}

{% block title %}Comentário{% endblock %}

{% block content %}


<div id="main4" class="block-color" style="text-align: center;">
    {% if user.is_authenticated %}
        <h1>Confirme a criação</h1><br>
        <form method="post" class="form-signin">
            {% csrf_token %}
            <div style="display: none;">
            {{ form.as_p }}
            </div>
            <button class="btn btn-secundary" type="submit">Confirmo</button>
        </form> <br>
        <button onclick="window.location.href='/'" class="btn btn-primary" style="display: inline;">Home</button>
        
    {% else %}
        <META http-equiv="refresh" content="0;URL=/"> 
    {% endif %}
    
</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %} 

{% block title %}Intin Livre{% endblock %}

{% block content %}

<script>

  function notification(value, id) {
    var x = document.getElementById(id).elements[0].value;
    if (x < value) {
        alert("O lançe não pode ser menor que o lançe inicial!");
        location.reload();
        return false;
    }
    else{
        alert("Parabéns seu lançe foi feito!");
        return true;
    }

    
    
}
</script>

{% if user.is_authenticated %}

    <nav class="navbar navbar-custom" >
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" style="vertical-align: center;" href="/"><img width="40" height="30" src="https://logodownload.org/wp-content/uploads/2016/08/Mercado-Livre-logo-6.png"></a>
        </div>
        <ul class="nav navbar-nav navbar-custom" style="margin-left: 50px;">
          <li class="active"><a class="color-custom" href="/my-throw/">Lançes</a></li>
          <li class="active"><a class="color-custom" href="/my-product/">Meus Produtos</a></li>
          <li class="active"><a class="color-custom" href="/create/">Vender</a></li>
        </ul>
        <form class="form-inline my-2 my-lg-0 nav navbar-nav" method="GET" action="{% url 'leilao:search' %}" style="margin-top: 6px;">
          {% csrf_token %}
          <div class="buttonInside center2">
          <input name="q" size="50" class="form-control mr-sm-2" type="text" placeholder="Buscar produto" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="search" value="search"><i class="material-icons">search</i></button>
          </div>
        </form>

        <p>{{user.name}}</p>
        <ul class="nav navbar-nav navbar-right navbar-custom">
           <li><a class="color-custom"><span class="glyphicon glyphicon-user"></span>{{user.username}}</a></li>
          <li><a class="color-custom" href="/accounts/logout"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
        </ul>
      </div>
    </nav>

    <div style="margin-left: 8%;">
      {%for x in object_list%}
          {% if x == False %}
            <h1>Desculpe a pesquisa não retornou resultados</h1>
    
          {%else%}
          {%if x.state%}
            <div class="box" style="text-align: center;">
              <img class="img1" src="{{ MEDIA_URL }}{{ x.image }}">
              <h3>{{x.name}}</h3>
              <h2>Lançe inicial de R${{x.startPrice}}</h2>
              {%if x.ultimoLance > 0%}
              <h5>O último Lançe foi R${{x.ultimoLance}}</h5>
              {%endif%}
              {%if x.state %}
              <h6>Acaba em {{x.Prazo}}</h6>
              {%if x.user.id == user.id%}
              <h3>Esse produto é seu!</h3>
              {%else%}
              <form method="GET" action="{% url 'leilao:throw' %}" id={{x.id}} onsubmit="return notification({{x.startPrice}}, {{x.id}})">
                <input size="5" type="text" name="lance">
                {%if x.ultimoLance > 0%}
                <input type="hidden" name="finalance" value={{x.ultimoLance}}>
                {%endif%}
                <input type="hidden" name="id" value={{x.id}}>
                <button class="btn btn-primary" type="submit">Dá lançe</button>
              </form>
              {%endif%}
            </div>
              {%else%}
              <h6>Encerrado</h6>
              {%if x.vendido %}
                <h3>Vendido à {{x.compradoPor}}</h3>
              {%endif%}
              {%endif%}
              
          {% endif %}
          {% endif %}
      {% endfor %}

    </div>


{% else %}
  
<nav class="navbar navbar-custom" >
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" style="vertical-align: center;" href="/"><img width="40" height="30" src="https://logodownload.org/wp-content/uploads/2016/08/Mercado-Livre-logo-6.png"></a>
    </div>
    <ul class="nav navbar-nav navbar-custom" style="margin-left: 50px;">
      <li class="active"><a class="color-custom" href="/my-throw/">Lançes</a></li>
      <li class="active"><a class="color-custom" href="/my-product/">Meus Produtos</a></li>
      <li class="active"><a class="color-custom" href="/create/">Vender</a></li>
    </ul>
     <form class="form-inline my-2 my-lg-0 nav navbar-nav" method="GET" action="{% url 'leilao:search' %}" style="margin-top: 6px;">
          {% csrf_token %}
          <div class="buttonInside center2">
          <input name="q" size="50" class="form-control mr-sm-2" type="text" placeholder="Buscar produto" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="search" value="search"><i class="material-icons">search</i></button>
          </div>
        </form>
    <ul class="nav navbar-nav navbar-right navbar-custom">
      <li><a class="color-custom" href="/signup/"><span class="glyphicon glyphicon-user"></span> Cadastre-se</a></li>
      <li><a class="color-custom" href="/accounts/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
  
<div style="margin-left: 8%;">
      {%for x in object_list%}
          {% if x == False %}
            <h1>Desculpe a pesquisa não retornou resultados</h1>
    
          {%else%}
          {%if x.state%}
            <div class="box" style="text-align: center;">
              <img class="img1" src="{{ MEDIA_URL }}{{ x.image }}">
              <h3>{{x.name}}</h3>
              <h2>Lançe inicial de R${{x.startPrice}}</h2>
              {%if x.ultimoLance > 0%}
              <h5>O último Lançe foi R${{x.ultimoLance}}</h5>
              {%endif%}
              {%if x.state %}
              <h6>Acaba em {{x.Prazo}}</h6>
              <h3>Faça login para ofertar</h3>
            </div>
              {%else%}
              <h6>Encerrado</h6>
              {%if x.vendido %}
                <h3>Vendido!</h3>
              {%endif%}
              {%endif%}
              
          {% endif %}
          {% endif %}
      {% endfor %}

    </div>

{% endif %}


{% endblock %}

templates/lances.html
{% extends 'base.html' %} 

{% block title %}Intin Livre{% endblock %}

{% block content %}


{% if user.is_authenticated %}

    <nav class="navbar navbar-custom" >
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" style="vertical-align: center;" href="/"><img width="40" height="30" src="https://logodownload.org/wp-content/uploads/2016/08/Mercado-Livre-logo-6.png"></a>
        </div>
        <ul class="nav navbar-nav navbar-custom" style="margin-left: 50px;">
          <li class="active"><a class="color-custom" href="/my-product/">Meus Produtos</a></li>
          <li class="active"><a class="color-custom" href="/create/">Vender</a></li>
        </ul>

        <p>{{user.name}}</p>
        <ul class="nav navbar-nav navbar-right navbar-custom">
           <li><a class="color-custom"><span class="glyphicon glyphicon-user"></span>{{user.username}}</a></li>
          <li><a class="color-custom" href="/accounts/logout"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
        </ul>
      </div>
    </nav>

    <div style="margin-left: 8%;">
      {%if object_list %}
      {%for x in object_list%}
            <div class="box" style="text-align: center;">
              <img class="img1" src="{{ MEDIA_URL }}{{ x.produto.image }}">
              <h3>{{x.produto.name}}</h3>
              <h5>Seu lance foi de R${{x.lance}}</h5>
              {%if x.produto.state %}
              <h6>Acaba em {{x.produto.Prazo}}</h6>
              <form method="GET">
                <input type="hidden" name="id" value={{x.id}}>
                <button class="btn btn-danger" type="submit">Desistir</button>
              </form>
              {%else%}
              <h6>Encerrado</h6>
              {%if x.bought %}
                <h3>Comprado por você!</h3>
              {%endif%}
              {%endif%}        
      {% endfor %}
      {%else%}
      <h1>Não há nada para mostar aqui!</h1>
      {%endif%}

    </div>


{% else %}
  
<nav class="navbar navbar-custom" >
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" style="vertical-align: center;" href="/"><img width="40" height="30" src="https://logodownload.org/wp-content/uploads/2016/08/Mercado-Livre-logo-6.png"></a>
    </div>
    <ul class="nav navbar-nav navbar-custom" style="margin-left: 50px;">
      <li class="active"><a class="color-custom" href="#">Lançes</a></li>
      <li class="active"><a class="color-custom" href="/my-product/">Meus Produtos</a></li>
      <li class="active"><a class="color-custom" href="/create/">Vender</a></li>
    </ul>
     <form class="form-inline my-2 my-lg-0 nav navbar-nav" method="GET" action="{% url 'leilao:search' %}" style="margin-top: 6px;">
          {% csrf_token %}
          <div class="buttonInside center2">
          <input name="q" size="50" class="form-control mr-sm-2" type="text" placeholder="Buscar produto" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="search" value="search"><i class="material-icons">search</i></button>
          </div>
        </form>
    <ul class="nav navbar-nav navbar-right navbar-custom">
      <li><a class="color-custom" href="#"><span class="glyphicon glyphicon-user"></span> Cadastre-se</a></li>
      <li><a class="color-custom" href="/accounts/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
  
<div style="margin-left: 8%;">
      {%for x in object_list%}
          {% if x == False %}
            <h1>Desculpe a pesquisa não retornou resultados</h1>
    
          {%else%}
            <div class="box" style="text-align: center;">
              <img class="img1" src="{{ MEDIA_URL }}{{ x.image }}">
              <h3>{{x.name}}</h3>
              <h5>Lançe inicial de R${{x.startPrice}}</h5>
              <h6>Acaba em {{x.Prazo}}<h6>
              <button class="btn btn-primary">Dá lançe</button>
            </div>
      {% endif %}
      {% endfor %}

    </div>

{% endif %}


{% endblock %}

templates/myproduct.html
{% extends 'base.html' %}

{% block title %}Meus Produtos{% endblock %}

{% block content %}

{% if user.is_authenticated %}

    <nav class="navbar navbar-custom" >
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" style="vertical-align: center;" href="/"><img width="40" height="30" src="https://logodownload.org/wp-content/uploads/2016/08/Mercado-Livre-logo-6.png"></a>
        </div>
        <ul class="nav navbar-nav navbar-custom" style="margin-left: 50px;">
          <li class="active"><a class="color-custom" href="/create/">Vender</a></li>
        </ul>

        <p>{{user.name}}</p>
        <ul class="nav navbar-nav navbar-right navbar-custom">
           <li><a class="color-custom"><span class="glyphicon glyphicon-user"></span>{{user.username}}</a></li>
          <li><a class="color-custom" href="/accounts/logout"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
        </ul>
      </div>
    </nav>

    <div style="margin-left: 8%;">
      {%if object_list %}
      {%for x in object_list%}
          {% if x == False %}
            <h1>Desculpe a pesquisa não retornou resultados</h1>
    
          {%else%}
            <div class="box" style="text-align: center;">
              <img class="img1" src="{{ MEDIA_URL }}{{ x.image }}">
              <h3>{{x.name}}</h3>
              {%if x.vendido%}
              <h5>Seu produto foi vendido à {{x.compradoPor}}</h5>
              {%else%}
              <h5>Lançe inicial de R${{x.startPrice}}</h5>
              <h6>Acaba em {{x.Prazo}}</h6>
              {%endif%}
              <form method="GET" action="{% url 'leilao:my' %}">
                <input type="hidden" name="id" value={{x.id}}>
                <button class="btn btn-danger" type="submit">Excluir</button>
              </form>
              <a href='{% url "leilao:update" x.pk %}'>Atualizar</a>
            </div>
          {% endif %}
      {% endfor %}
      {%else%}
      <h1>Não há nada para mostar aqui!</h1>
      {%endif%}

    </div>


{% else %}
  
<META http-equiv="refresh" content="0;URL=/accounts/login/"> 

{% endif %}



{% endblock %}

templates/productup.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Atualizar produto{% endblock %}


{% block content %}
{% if user.is_authenticated %}
<div class="upper">
   <a class="navbar-brand" style="vertical-align: center;" href="/"><img width="160" height="100" src="https://negocioonlineja.com/wp-content/uploads/2018/02/Mercado-Livre-logo-1.png"></a>
</div>

<div class="lower">
    
</div>

<div class="center3">  
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        {% for field in form.visible_fields %}
          <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field|add_class:'form-control' }}
              {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
       <div style="text-align: center;">
            <input type="submit" value="Vender"/>
        </div>
    </form>
</div>

{%else%}
  <META http-equiv="refresh" content="0;URL=/accounts/login/"> 

{%endif%}

  
{% endblock %}

templates/produto.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Criar produto{% endblock %}


{% block content %}
{% if user.is_authenticated %}
<div class="upper">
   <a class="navbar-brand" style="vertical-align: center;" href="/"><img width="160" height="100" src="https://negocioonlineja.com/wp-content/uploads/2018/02/Mercado-Livre-logo-1.png"></a>
</div>

<div class="lower">
    
</div>

<div class="center3">  
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form.visible_fields %}
          <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">

              {% if field.name == 'Prazo' %}
                <input type="date" min={{date}}
                max="3000-12-31" class="form-control" id="id_Prazo" name="Prazo" required="">
              {%endif%}
              {% if field.name != 'Prazo' %}
              {{ field|add_class:'form-control' }}
              {%endif%}

              {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
       <div style="text-align: center;">
            <input type="submit" value="Vender"/>
        </div>
    </form>
</div>

{%else%}
  <META http-equiv="refresh" content="0;URL=/accounts/login/"> 

{%endif%}

  
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}




<div class="upper">
   <a class="navbar-brand" style="vertical-align: center;" href="/"><img width="160" height="100" src="https://negocioonlineja.com/wp-content/uploads/2018/02/Mercado-Livre-logo-1.png"></a>
</div>
<div class="lower">
    
</div>

<div class="center4 top-buffer">  
        <div class="text-center">
        <div style="margin-top:20px; width: auto; margin-right: 50px; margin-left: 50px;">
        <form method="POST" class="form-signin">
                {% csrf_token %}

                <input style="margin-top: 10px;"  "type="text" name="username" class="form-control" placeholder="UserName" required id="id_username">
                <p>Não use caracters especiais como: @, #, $</p><br>
                
                <input required type="password" name="password1" class="form-control" placeholder="Senha" id="id_password1"><br>
                <ul style="text-align: left;">
                    <li>Sua senha não pode ser tão parecida com suas outras informações pessoais.</li>
                    <li>Sua senha precisa conter pelo menos 8 caracteres.</li>
                    <li>Sua senha não pode ser uma senha habitualmente utilizada.</li>
                    <li>Sua senha não pode ser inteiramente numérica.</li>
                </ul>
                 

                <input required type="password" name="password2" class="form-control" placeholder="Confirme Senha" id="id_password2"><br>

                <div class="btn-group" role="group" aria-label="Basic example">
                
                <button style="margin: 5px; " type="submit" name="submit" class="btn btn-primary">Cadastrar</button>

                </div>
                </div>
                <div class="form-group">

        </form>
                
        </form>
     </div>   
    </div>
</div>

{% endblock %}